apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-nvidia
  namespace: argocd
  labels:
    env: prod
    arch: amd64
    gpu: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/predator-analytics/nexus-core.git
    path: charts/predator
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.env
          value: prod
        - name: ollama.enabled
          value: "true"
        - name: ollama.gpu
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: predator-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
