
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predator-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: predator-root
    env: production
spec:
  project: default
  source:
    repoURL: https://github.com/predator-analytics/nexus-core.git
    path: charts/predator
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: predator-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
