apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-qdrant
spec:
  serviceName: {{ .Release.Name }}-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-qdrant
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-qdrant
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: data
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
