apiVersion: v1
kind: Service
metadata:
  name: {{ include "predator-umbrella.fullname" . }}-mlflow
  labels:
    {{- include "predator-umbrella.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "predator-umbrella.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
