apiVersion: v1
kind: Service
metadata:
  name: {{ include "predator-umbrella.fullname" . }}-ollama
  labels:
    {{- include "predator-umbrella.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "predator-umbrella.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
