apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-processor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-processor
    spec:
      containers:
        - name: processor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
